IMAGE:
  WIDTH: 640
  HEIGHT: 480

XYCAR:
  START_SPEED: 9.0
  MAX_SPEED: 10.0
  MIN_SPEED: 3.5
  SPEED_CONTROL_THRESHOLD: 20
  ACCELERATION_STEP: 1.0
  DECELERATION_STEP: 3.0

PID:
  P_GAIN: 0.45
  I_GAIN: 0.0008
  D_GAIN: 0.175

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: true
